# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

fib = [1, 2]

last_term = fib[len(fib) - 1]
second_last_term = fib[len(fib) - 2]

while last_term <= 4000000:
	fib.append(last_term + second_last_term)
	last_term = fib[len(fib) - 1]
	second_last_term = fib[len(fib) - 2]

del fib[len(fib) - 1]

total = 0
for n in range(0, len(fib)):
	if fib[n - 1] % 2 == 0:
		total += fib[n - 1]

print(total)

# Answer: 4613732